### ISSUE TITLE
To-Do. Complete This list for v1.

### ISSUE THREAD

**Issue by saq1610** [Arelos/arelos#4]
### To-Do
- [ ] Get a fully working top Panel (Mate Panel)
- [X] Icon theme
- [X] Gtk theme (has some huge bugs - Xenite)
- [ ] Complete desktop experience

Please suggest some things to add to this list. I am sure I have missed some important things.
